name: Deploy test frontend

on:
  push:
    branches: ['test']

jobs: 
  Deploy-frontend:
    name: "Deploy frontend"
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Debug lockfile
        run: |
          cd frontend
          node -v
          npm -v
          ls -la
          test -f package-lock.json && echo "lockfile exists"
          grep -n "@emnapi" package-lock.json || true
          npm pkg get dependencies
          npm pkg get devDependencies

          
      - name: Show npm tree resolution
        run: |
          cd frontend
          npm install --package-lock-only
          git diff -- package-lock.json || true

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci


      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      - name: "Deploy frontend"
        env:
          SSH_USERNAME: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY_2 }}
          SSH_HOST: ${{ secrets.SSH_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT_2 }}
        run: |
          set -e
          
          mkdir -p ~/.ssh/
          printf "%s" "$SSH_KEY" > ~/.ssh/vps.key
          chmod 600 ~/.ssh/vps.key

          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

          scp -i ~/.ssh/vps.key \
          -P "$SSH_PORT" \
          -r ./frontend/dist/* \
          "$SSH_USERNAME@$SSH_HOST:/var/www/test.savefuel/dist"
          
          ssh -i ~/.ssh/vps.key \
          -p "$SSH_PORT" \
          "$SSH_USERNAME@$SSH_HOST" << 'EOF'

          sudo systemctl reload nginx
